# Site settings
title: "剑BLOG"
email: blancobkoy@sina.com
description: "全栈式技术博客"
baseurl: ""
url: "http://blancobkoy.github.io/"
title_description: "废话就不说了"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: ""
disqus_account: blancoBlog
github_repository: https://github.com/blancobkoy/blancobkoy.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _blancobkoy
github_username:  blancobkoy

# Footer
footer_left: "Made with 剑"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/blancobkoy/blancobkoy.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
